### ISSUE TITLE
add about us

### ISSUE THREAD

**Issue by bhumimah04** [MiniProject-Internal/Search-My-Recipe#2]

**Comment by SakshiParate03** [comment]
Added About me Information 
& added picture

**Comment by SakshiParate03** [comment]
completed link deployment
& added images

**Comment by AaryaRaut24** [comment]
added images to about us file

**Comment by AaryaRaut24** [comment]
link published on website(deployment done)

**Comment by Samruddhi-22** [comment]
READme file created
